import LessLibraryAbi from "../data/LessLibraryAbi";
import StakingAbi from "../data/StakingAbi";
import PresaleFactoryAbi from "../data/PresaleFactoryAbi";
import ERC20Abi from "../data/ERC20Abi";
import PresalePublicAbi from "../data/PresalePublicAbi";

const IS_PRODUCTION = false;
const IS_TESTING_ON_ROPSTEN = false;
const SHOW_CONSOLE_LOGS = true;

export default {
  IS_PRODUCTION,
  IS_TESTING_ON_ROPSTEN,
  SHOW_CONSOLE_LOGS,
  version: IS_PRODUCTION ? 'Mainnet beta' : IS_TESTING_ON_ROPSTEN ? 'Ropsten beta' : 'Kovan beta',
  isMainnetOrTestnet: IS_PRODUCTION ? 'mainnet' : 'testnet',
  netType: IS_PRODUCTION ? 'mainnet' : IS_TESTING_ON_ROPSTEN ? 'ropsten' : 'kovan',
  links: {
    twitter: 'https://twitter.com/',
    telegram: 'https://t.me/',
    medium: 'https://medium.com/',
    github: 'https://github.com/',
    reddit: 'https://www.reddit.com/',
    discord: 'https://discord.gg/',
    email: 'support@mail.com',
    policy: '',
  },
  apis: {
    '0x': IS_PRODUCTION
      ? 'https://api.0x.org'
      : IS_TESTING_ON_ROPSTEN
        ? 'https://ropsten.api.0x.org/'
        : 'https://kovan.api.0x.org/',
  },
  keys: {
    infura: '',
  },
  chainIds: {
    mainnet: {
      'Ethereum': {
        name: 'Ethereum',
        id: [1, '0x1', '0x01'],
      },
      'Binance-Smart-Chain': {
        name: 'Binance smart chain',
        id: [56, '0x38'],
      },
      'Matic': {
        name: 'Matic',
        id: [137, '0x137'],
      },
    },
    testnet: {
      'Ethereum': !IS_TESTING_ON_ROPSTEN
        ? {
            name: 'Kovan testnet',
            id: [42, '0x2a'],
          }
        : {
            name: 'Ropsten testnet',
            id: [3, '0x3'],
          },
      'Binance-Smart-Chain': {
        name: 'Binance smart chain testnet',
        id: [97, '0x61'],
      },
      // todo
      'Matic': {
        name: 'Matic testnet',
        id: [137, '0x137'],
      },
    },
  },
  addresses: {
    mainnet: {
      // todo
      // 'Ethereum': {
      //   LessToken: '0xa372d1d35041714092900B233934fB2D002755E2',
      //   LessLibrary: '0x46589Ab934277E44A5060f3273761b86396d5429',
      //   Staking: '0xF4Fa7Fd880Eb889B4829126d89C4F09304B73270',
      //   PresaleFactory: '0xB9733F217111A845A268d1D98EE91800907860e2',
      //   PresalePublic: '0xeA63Bfc235c1f70BE88287BCed13A42550C40DF3',
      // },
      // 'Binance-Smart-Chain': {
      //   LessToken: '0xa372d1d35041714092900B233934fB2D002755E2',
      //   LessLibrary: '0x46589Ab934277E44A5060f3273761b86396d5429',
      //   Staking: '0xF4Fa7Fd880Eb889B4829126d89C4F09304B73270',
      //   PresaleFactory: '0xB9733F217111A845A268d1D98EE91800907860e2',
      //   PresalePublic: '0xeA63Bfc235c1f70BE88287BCed13A42550C40DF3',
      // },
    },
    testnet: {
      // 'Ethereum': {
      //   LessToken: '0xa372d1d35041714092900B233934fB2D002755E2',
      //   LessLibrary: '0x46589Ab934277E44A5060f3273761b86396d5429',
      //   Staking: '0xF4Fa7Fd880Eb889B4829126d89C4F09304B73270',
      //   PresaleFactory: '0xB9733F217111A845A268d1D98EE91800907860e2',
      //   PresalePublic: '0xeA63Bfc235c1f70BE88287BCed13A42550C40DF3',
      // },
      'Ethereum': {
        // LessToken: '0xa372d1d35041714092900b233934fb2d002755e2',
        // LessToken: '0xa372d1d35041714092900b233934fb2d002755e2',
        LessToken: '0xE29dA66439BcBdB71D508f41bAd13250F561E38f',
        // LessLibrary: '0x42d58A23259Fb09A02384d80772Ee8236ef63732',
        // LessLibrary: '0x4b01de89936046228d87dad26b7796ea8f424fa4',
        LessLibrary: '0x46d240A3627Ebf2F507C91c9aA604d6535cCb07a',
        // Staking: '0x2D01C2d1adA5D0311A8d16aDA865662a3658C91F',
        // Staking: '0xf3016a3c8ddd673535a058b2b86aa6299639e933',
        Staking: '0x1756715185E7d1AF64ec555591A6B8ea64D07f8E',
        // PresaleFactory: '0xe9e9a8bacEC4894bDCBf4F63f57A9A5F0D8432BD',
        // PresaleFactory: '0x33918Fa73f367000c0911d8dD5949684e4ca3468',
        PresaleFactory: '0x8DD3992F6968C08283F8cDB3f6e41d10dBa2Df5c',
        PresalePublic: '0xeA63Bfc235c1f70BE88287BCed13A42550C40DF3', // todo
      },
      'Binance-Smart-Chain': {
        // todo
        // LessToken: '0xa372d1d35041714092900B233934fB2D002755E2',
        // LessLibrary: '0x46589Ab934277E44A5060f3273761b86396d5429',
        // Staking: '0xF4Fa7Fd880Eb889B4829126d89C4F09304B73270',
        // PresaleFactory: '0xB9733F217111A845A268d1D98EE91800907860e2',
        // PresalePublic: '0xeA63Bfc235c1f70BE88287BCed13A42550C40DF3',
      },
    },
  },
  abis: {
    mainnet: {},
    testnet: {
      Ethereum: {
        LessToken: ERC20Abi,
        LessLibrary: LessLibraryAbi,
        Staking: StakingAbi,
        PresaleFactory: PresaleFactoryAbi,
        PresalePublic: PresalePublicAbi,
      },
      // Ethereum: {
      //   LessToken: [
      //     {
      //       inputs: [
      //         { internalType: 'string', name: 'name', type: 'string' },
      //         { internalType: 'string', name: 'symbol', type: 'string' },
      //       ],
      //       stateMutability: 'nonpayable',
      //       type: 'constructor',
      //     },
      //     {
      //       anonymous: false,
      //       inputs: [
      //         { indexed: true, internalType: 'address', name: 'owner', type: 'address' },
      //         { indexed: true, internalType: 'address', name: 'spender', type: 'address' },
      //         { indexed: false, internalType: 'uint256', name: 'value', type: 'uint256' },
      //       ],
      //       name: 'Approval',
      //       type: 'event',
      //     },
      //     {
      //       anonymous: false,
      //       inputs: [
      //         { indexed: true, internalType: 'address', name: 'from', type: 'address' },
      //         { indexed: true, internalType: 'address', name: 'to', type: 'address' },
      //         { indexed: false, internalType: 'uint256', name: 'value', type: 'uint256' },
      //       ],
      //       name: 'Transfer',
      //       type: 'event',
      //     },
      //     {
      //       inputs: [
      //         { internalType: 'address', name: 'owner', type: 'address' },
      //         { internalType: 'address', name: 'spender', type: 'address' },
      //       ],
      //       name: 'allowance',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [
      //         { internalType: 'address', name: 'spender', type: 'address' },
      //         { internalType: 'uint256', name: 'amount', type: 'uint256' },
      //       ],
      //       name: 'approve',
      //       outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
      //       name: 'balanceOf',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'decimals',
      //       outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [
      //         { internalType: 'address', name: 'spender', type: 'address' },
      //         { internalType: 'uint256', name: 'subtractedValue', type: 'uint256' },
      //       ],
      //       name: 'decreaseAllowance',
      //       outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [
      //         { internalType: 'address', name: 'spender', type: 'address' },
      //         { internalType: 'uint256', name: 'addedValue', type: 'uint256' },
      //       ],
      //       name: 'increaseAllowance',
      //       outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [
      //         { internalType: 'address', name: 'to', type: 'address' },
      //         { internalType: 'uint256', name: 'amount', type: 'uint256' },
      //       ],
      //       name: 'mint',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'name',
      //       outputs: [{ internalType: 'string', name: '', type: 'string' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'symbol',
      //       outputs: [{ internalType: 'string', name: '', type: 'string' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'totalSupply',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [
      //         { internalType: 'address', name: 'recipient', type: 'address' },
      //         { internalType: 'uint256', name: 'amount', type: 'uint256' },
      //       ],
      //       name: 'transfer',
      //       outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [
      //         { internalType: 'address', name: 'sender', type: 'address' },
      //         { internalType: 'address', name: 'recipient', type: 'address' },
      //         { internalType: 'uint256', name: 'amount', type: 'uint256' },
      //       ],
      //       name: 'transferFrom',
      //       outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //   ],
      //   LessLibrary: [
      //     {
      //       inputs: [
      //         { internalType: 'address', name: '_dev', type: 'address' },
      //         { internalType: 'address payable', name: '_vault', type: 'address' },
      //       ],
      //       stateMutability: 'nonpayable',
      //       type: 'constructor',
      //     },
      //     {
      //       anonymous: false,
      //       inputs: [
      //         { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      //         { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
      //       ],
      //       name: 'OwnershipTransferred',
      //       type: 'event',
      //     },
      //     {
      //       inputs: [{ internalType: 'address', name: '_presale', type: 'address' }],
      //       name: 'addPresaleAddress',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'uint256', name: 'amount', type: 'uint256' }],
      //       name: 'calculateFee',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'address', name: '_newDev', type: 'address' }],
      //       name: 'changeDev',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getDev',
      //       outputs: [{ internalType: 'address', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getFactoryAddress',
      //       outputs: [{ internalType: 'address', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getMinCreatorStakedBalance',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getMinInvestorBalance',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getMinUnstakeTime',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getMinVoterBalance',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getMinYesVotesThreshold',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
      //       name: 'getPresaleAddress',
      //       outputs: [{ internalType: 'address', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getPresalesCount',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'address', name: 'sender', type: 'address' }],
      //       name: 'getStakedSafeBalance',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getUniswapRouter',
      //       outputs: [{ internalType: 'address', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getVaultAddress',
      //       outputs: [{ internalType: 'address payable', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getVotingTime',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'owner',
      //       outputs: [{ internalType: 'address', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'renounceOwnership',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'safeStakingPool',
      //       outputs: [{ internalType: 'contract IStaking', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'address', name: '_factory', type: 'address' }],
      //       name: 'setFactoryAddress',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [
      //         { internalType: 'uint256', name: 'id', type: 'uint256' },
      //         { internalType: 'address', name: '_newAddress', type: 'address' },
      //       ],
      //       name: 'setPresaleAddress',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'address', name: '_staking', type: 'address' }],
      //       name: 'setStakingAddress',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'address', name: '_uniswapRouter', type: 'address' }],
      //       name: 'setUniswapRouter',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'uint256', name: '_newVotingTime', type: 'uint256' }],
      //       name: 'setVotingTime',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
      //       name: 'transferOwnership',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //   ],
      //   Staking: [
      //     {
      //       inputs: [
      //         { internalType: 'address', name: '_safeToken', type: 'address' },
      //         { internalType: 'address', name: '_safeLibrary', type: 'address' },
      //       ],
      //       stateMutability: 'nonpayable',
      //       type: 'constructor',
      //     },
      //     {
      //       anonymous: false,
      //       inputs: [
      //         { indexed: true, internalType: 'address', name: 'from', type: 'address' },
      //         { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      //       ],
      //       name: 'Staked',
      //       type: 'event',
      //     },
      //     {
      //       anonymous: false,
      //       inputs: [
      //         { indexed: true, internalType: 'address', name: 'from', type: 'address' },
      //         { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      //       ],
      //       name: 'Unstaked',
      //       type: 'event',
      //     },
      //     {
      //       inputs: [{ internalType: 'address', name: '', type: 'address' }],
      //       name: 'accountInfos',
      //       outputs: [
      //         { internalType: 'uint256', name: 'balance', type: 'uint256' },
      //         { internalType: 'uint256', name: 'lastStakedTimestamp', type: 'uint256' },
      //         { internalType: 'uint256', name: 'lastUnstakedTimestamp', type: 'uint256' },
      //       ],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'address', name: 'staker', type: 'address' }],
      //       name: 'getAccountInfo',
      //       outputs: [
      //         { internalType: 'uint256', name: '', type: 'uint256' },
      //         { internalType: 'uint256', name: '', type: 'uint256' },
      //         { internalType: 'uint256', name: '', type: 'uint256' },
      //       ],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getStakedAmount',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'safeLibrary',
      //       outputs: [{ internalType: 'contract LessLibrary', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'safeToken',
      //       outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'address', name: '_newInfo', type: 'address' }],
      //       name: 'setLibraryAddress',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'uint256', name: '_amount', type: 'uint256' }],
      //       name: 'stake',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'uint256', name: '_amount', type: 'uint256' }],
      //       name: 'unstake',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //   ],
      //   PresaleFactory: [
      //     {
      //       inputs: [
      //         { internalType: 'address', name: '_bscsInfoAddress', type: 'address' },
      //         { internalType: 'address', name: '_bscsToken', type: 'address' },
      //         { internalType: 'address', name: '_safeStakingPool', type: 'address' },
      //       ],
      //       stateMutability: 'nonpayable',
      //       type: 'constructor',
      //     },
      //     {
      //       anonymous: false,
      //       inputs: [
      //         { indexed: false, internalType: 'uint256', name: 'presaleId', type: 'uint256' },
      //         { indexed: false, internalType: 'address', name: 'creator', type: 'address' },
      //         { indexed: false, internalType: 'address', name: 'tokenAddress', type: 'address' },
      //         {
      //           indexed: false,
      //           internalType: 'uint256',
      //           name: 'timeForLiquidity',
      //           type: 'uint256',
      //         },
      //       ],
      //       name: 'CertifiedAutoPresaleCreated',
      //       type: 'event',
      //     },
      //     {
      //       anonymous: false,
      //       inputs: [
      //         { indexed: false, internalType: 'uint256', name: 'presaleId', type: 'uint256' },
      //         { indexed: false, internalType: 'address', name: 'creator', type: 'address' },
      //         { indexed: false, internalType: 'address', name: 'tokenAddress', type: 'address' },
      //       ],
      //       name: 'CertifiedPresaleCreated',
      //       type: 'event',
      //     },
      //     {
      //       anonymous: false,
      //       inputs: [
      //         { indexed: false, internalType: 'uint256', name: 'presaleId', type: 'uint256' },
      //         { indexed: false, internalType: 'address', name: 'creator', type: 'address' },
      //         { indexed: false, internalType: 'address', name: 'tokenAddress', type: 'address' },
      //         {
      //           indexed: false,
      //           internalType: 'uint256',
      //           name: 'timeForLiquidity',
      //           type: 'uint256',
      //         },
      //       ],
      //       name: 'PublicPresaleCreated',
      //       type: 'event',
      //     },
      //     {
      //       anonymous: false,
      //       inputs: [
      //         { indexed: true, internalType: 'address', name: 'from', type: 'address' },
      //         { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
      //       ],
      //       name: 'Received',
      //       type: 'event',
      //     },
      //     {
      //       inputs: [
      //         {
      //           components: [
      //             { internalType: 'address', name: 'tokenAddress', type: 'address' },
      //             { internalType: 'uint256', name: 'tokenPriceInWei', type: 'uint256' },
      //             { internalType: 'uint256', name: 'hardCapInWei', type: 'uint256' },
      //             { internalType: 'uint256', name: 'softCapInWei', type: 'uint256' },
      //             { internalType: 'uint256', name: 'maxInvestInWei', type: 'uint256' },
      //             { internalType: 'uint256', name: 'minInvestInWei', type: 'uint256' },
      //             { internalType: 'uint256', name: 'openTime', type: 'uint256' },
      //             { internalType: 'uint256', name: 'closeTime', type: 'uint256' },
      //             { internalType: 'uint8', name: 'presaleType', type: 'uint8' },
      //             { internalType: 'bool', name: 'liquidity', type: 'bool' },
      //             { internalType: 'bool', name: 'automatically', type: 'bool' },
      //             { internalType: 'bool', name: 'whitelisted', type: 'bool' },
      //             { internalType: 'address[]', name: 'whitelist', type: 'address[]' },
      //             { internalType: 'bool', name: 'vesting', type: 'bool' },
      //           ],
      //           internalType: 'struct PresaleFactory.PresaleInfo',
      //           name: '_info',
      //           type: 'tuple',
      //         },
      //         {
      //           components: [
      //             { internalType: 'uint256', name: 'listingPriceInWei', type: 'uint256' },
      //             { internalType: 'uint256', name: 'lpTokensLockDurationInDays', type: 'uint256' },
      //             { internalType: 'uint8', name: 'liquidityPercentageAllocation', type: 'uint8' },
      //             { internalType: 'uint256', name: 'liquidityAllocationTime', type: 'uint256' },
      //           ],
      //           internalType: 'struct PresaleFactory.PresalePancakeSwapInfo',
      //           name: '_cakeInfo',
      //           type: 'tuple',
      //         },
      //         {
      //           components: [
      //             { internalType: 'bytes32', name: 'saleTitle', type: 'bytes32' },
      //             { internalType: 'bytes32', name: 'linkTelegram', type: 'bytes32' },
      //             { internalType: 'bytes32', name: 'linkGithub', type: 'bytes32' },
      //             { internalType: 'bytes32', name: 'linkTwitter', type: 'bytes32' },
      //             { internalType: 'bytes32', name: 'linkWebsite', type: 'bytes32' },
      //             { internalType: 'string', name: 'linkLogo', type: 'string' },
      //             { internalType: 'string', name: 'description', type: 'string' },
      //             { internalType: 'string', name: 'whitepaper', type: 'string' },
      //           ],
      //           internalType: 'struct PresaleFactory.PresaleStringInfo',
      //           name: '_stringInfo',
      //           type: 'tuple',
      //         },
      //       ],
      //       name: 'createPresalePublic',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'address payable', name: '_newFactory', type: 'address' }],
      //       name: 'migrateTo',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'owner',
      //       outputs: [{ internalType: 'address', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'safeLibrary',
      //       outputs: [{ internalType: 'contract LessLibrary', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'safeStakingPool',
      //       outputs: [{ internalType: 'contract Staking', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'token',
      //       outputs: [{ internalType: 'contract ERC20', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     { stateMutability: 'payable', type: 'receive' },
      //   ],
      //   PresalePublic: [
      //     {
      //       inputs: [
      //         { internalType: 'address', name: '_factory', type: 'address' },
      //         { internalType: 'address', name: '_library', type: 'address' },
      //         { internalType: 'address', name: '_platformOwner', type: 'address' },
      //         { internalType: 'address', name: '_devAddress', type: 'address' },
      //       ],
      //       stateMutability: 'nonpayable',
      //       type: 'constructor',
      //     },
      //     {
      //       inputs: [],
      //       name: 'addLiquidity',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'cancelPresale',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'uint256', name: '_newCloseTime', type: 'uint256' }],
      //       name: 'changeCloseTimeVoting',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [
      //         { internalType: 'uint256', name: '_newOpenTime', type: 'uint256' },
      //         { internalType: 'uint256', name: '_newCloseTime', type: 'uint256' },
      //       ],
      //       name: 'changePresaleTime',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'claimTokens',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'address', name: '', type: 'address' }],
      //       name: 'claimed',
      //       outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'closeTimePresale',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'closeTimeVoting',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'collectFundsRaised',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'description',
      //       outputs: [{ internalType: 'string', name: '', type: 'string' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getPresaleId',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'getUnsoldTokens',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'hardCap',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [
      //         { internalType: 'address[2]', name: '_creatorToken', type: 'address[2]' },
      //         {
      //           internalType: 'uint256[5]',
      //           name: '_priceTokensForSaleLiquiditySoftHard',
      //           type: 'uint256[5]',
      //         },
      //         { internalType: 'uint8', name: '_liquidityAlloc', type: 'uint8' },
      //         {
      //           internalType: 'uint256[5]',
      //           name: '_liqPriceDurationAllocTimeOpenClose',
      //           type: 'uint256[5]',
      //         },
      //       ],
      //       name: 'init',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     { inputs: [], name: 'invest', outputs: [], stateMutability: 'payable', type: 'function' },
      //     {
      //       inputs: [{ internalType: 'address', name: '', type: 'address' }],
      //       name: 'investments',
      //       outputs: [
      //         { internalType: 'uint256', name: 'amountEth', type: 'uint256' },
      //         { internalType: 'uint256', name: 'amountTokens', type: 'uint256' },
      //       ],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'lessLib',
      //       outputs: [{ internalType: 'contract LessLibrary', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'linkGithub',
      //       outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'linkLogo',
      //       outputs: [{ internalType: 'string', name: '', type: 'string' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'linkTelegram',
      //       outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'linkTwitter',
      //       outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'linkWebsite',
      //       outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'liquidityAllocation',
      //       outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'liquidityAllocationTime',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'liquidityLockDuration',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'listingPrice',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'maxInvestInWei',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'minInvestInWei',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'noVotes',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'openTimePresale',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'participants',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'pricePerToken',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'raisedAmount',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'refundLpTokens',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'saleTitle',
      //       outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'uint256', name: '_id', type: 'uint256' }],
      //       name: 'setPresaleId',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [
      //         { internalType: 'bytes32', name: '_saleTitle', type: 'bytes32' },
      //         { internalType: 'bytes32', name: '_linkTelegram', type: 'bytes32' },
      //         { internalType: 'bytes32', name: '_linkGithub', type: 'bytes32' },
      //         { internalType: 'bytes32', name: '_linkTwitter', type: 'bytes32' },
      //         { internalType: 'bytes32', name: '_linkWebsite', type: 'bytes32' },
      //         { internalType: 'string', name: '_linkLogo', type: 'string' },
      //         { internalType: 'string', name: '_description', type: 'string' },
      //         { internalType: 'string', name: '_whitepaper', type: 'string' },
      //       ],
      //       name: 'setStringInfo',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'softCap',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'token',
      //       outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'tokenDecimals',
      //       outputs: [{ internalType: 'uint8', name: '', type: 'uint8' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'tokenMagnitude',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'tokensForLiquidity',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'tokensLeft',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'unlockEthTime',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'bool', name: 'yes', type: 'bool' }],
      //       name: 'vote',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [{ internalType: 'address', name: '', type: 'address' }],
      //       name: 'voters',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'whitepaper',
      //       outputs: [{ internalType: 'string', name: '', type: 'string' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [
      //         { internalType: 'address payable', name: 'to', type: 'address' },
      //         { internalType: 'uint256', name: 'amount', type: 'uint256' },
      //       ],
      //       name: 'withdrawInvestment',
      //       outputs: [],
      //       stateMutability: 'nonpayable',
      //       type: 'function',
      //     },
      //     {
      //       inputs: [],
      //       name: 'yesVotes',
      //       outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      //       stateMutability: 'view',
      //       type: 'function',
      //     },
      //     { stateMutability: 'payable', type: 'receive' },
      //   ],
      // },
    },
  },
};
